//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSUARIO()
        {
            this.TBITACORA = new HashSet<TBITACORA>();
        }
    
        public long ConsecutivoUsuario { get; set; }
        public string Correo { get; set; }
        public string Contrasenna { get; set; }
        public string NombreCompleto { get; set; }
        public int TipoUsuario { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBITACORA> TBITACORA { get; set; }
        public virtual TPERFIL TPERFIL { get; set; }
    }
}
