//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.BaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbMartesEntities : DbContext
    {
        public dbMartesEntities()
            : base("name=dbMartesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBITACORA> TBITACORA { get; set; }
        public virtual DbSet<TPERFIL> TPERFIL { get; set; }
        public virtual DbSet<TUSUARIO> TUSUARIO { get; set; }
    }
}
