//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBITACORA
    {
        public long ConsecutivoError { get; set; }
        public long ConsecutivoUsuario { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int CodigoError { get; set; }
        public string Descripcion { get; set; }
        public string Origen { get; set; }
    
        public virtual TUSUARIO TUSUARIO { get; set; }
    }
}
