//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KN_API.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUSUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUSUARIO()
        {
            this.TBITACORA = new HashSet<TBITACORA>();
        }
    
        public long ConsecutivoUsuario { get; set; }
        public string Correo { get; set; }
        public string Password { get; set; }
        public string NombreCompleto { get; set; }
        public int TipoUsuario { get; set; }
        public bool Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBITACORA> TBITACORA { get; set; }
        public virtual TPERFIL TPERFIL { get; set; }
    }
}
